#!/bin/bash
# ============================================================
# MONEY MACHINE - CLONE MACHINE
# Digital Franchising: Duplicate the entire business in minutes
# ============================================================
# Usage: ./clone_machine.sh <new_niche>
# Example: ./clone_machine.sh ai_tools
#          ./clone_machine.sh crypto
#          ./clone_machine.sh faith
# ============================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Get the new niche name
NEW_NICHE="${1:-}"

if [ -z "$NEW_NICHE" ]; then
    echo -e "${RED}❌ Error: Please provide a niche name${NC}"
    echo ""
    echo "Usage: $0 <niche_name>"
    echo ""
    echo "Examples:"
    echo "  $0 ai_tools      # AI & Automation niche"
    echo "  $0 crypto        # Cryptocurrency niche"
    echo "  $0 faith         # Spiritual/Religious niche"
    echo "  $0 fitness       # Health & Fitness niche"
    echo "  $0 gaming        # Gaming niche"
    echo "  $0 parenting     # Parenting niche"
    echo "  $0 pets          # Pet care niche"
    echo "  $0 travel        # Travel niche"
    exit 1
fi

# Configuration
SOURCE_DIR="$(cd "$(dirname "$0")" && pwd)"
PARENT_DIR="$(dirname "$SOURCE_DIR")"
TARGET_DIR="${PARENT_DIR}/Money-Machine-${NEW_NICHE}"
NICHE_UPPER=$(echo "$NEW_NICHE" | tr '[:lower:]' '[:upper:]')
NICHE_TITLE=$(echo "$NEW_NICHE" | sed 's/_/ /g' | sed 's/\b\(.\)/\u\1/g')

echo -e "${BLUE}🔄 MONEY MACHINE CLONE SCRIPT${NC}"
echo "============================================"
echo -e "Source: ${CYAN}${SOURCE_DIR}${NC}"
echo -e "Target: ${CYAN}${TARGET_DIR}${NC}"
echo -e "Niche:  ${CYAN}${NICHE_TITLE}${NC}"
echo "============================================"
echo ""

# Check if target already exists
if [ -d "$TARGET_DIR" ]; then
    echo -e "${YELLOW}⚠️  Target directory already exists!${NC}"
    read -p "Overwrite? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
    fi
    rm -rf "$TARGET_DIR"
fi

# Step 1: Copy entire repo
echo "📁 Copying repository..."
cp -r "$SOURCE_DIR" "$TARGET_DIR"
echo -e "${GREEN}✅ Repository copied${NC}"

# Step 2: Remove git history (fresh start)
echo "🧹 Cleaning git history..."
rm -rf "${TARGET_DIR}/.git"
echo -e "${GREEN}✅ Git history removed${NC}"

# Step 3: Update configuration files
echo "⚙️  Updating configurations..."

# Update README
if [ -f "${TARGET_DIR}/README.md" ]; then
    sed -i "s/Money Machine/Money Machine - ${NICHE_TITLE}/g" "${TARGET_DIR}/README.md"
    sed -i "s/Elite Money Machine/Elite Money Machine - ${NICHE_TITLE}/g" "${TARGET_DIR}/README.md"
fi

# Update railway.json
if [ -f "${TARGET_DIR}/railway.json" ]; then
    sed -i "s/money-machine/money-machine-${NEW_NICHE}/g" "${TARGET_DIR}/railway.json"
fi

# Step 4: Create niche-specific configuration
echo "🎯 Creating niche configuration..."

cat > "${TARGET_DIR}/config/niche_config.py" << EOF
"""
============================================================
NICHE CONFIGURATION: ${NICHE_UPPER}
Generated by Clone Machine
============================================================
"""

from dataclasses import dataclass
from typing import List

@dataclass
class NicheConfig:
    """Configuration for ${NICHE_TITLE} niche"""
    
    # Niche Identity
    name: str = "${NEW_NICHE}"
    display_name: str = "${NICHE_TITLE}"
    tag: str = "${NICHE_UPPER}_01"
    
    # Content Strategy
    primary_keywords: List[str] = None
    secondary_keywords: List[str] = None
    
    # Monetization
    primary_affiliate_network: str = "clickbank"
    own_product_keywords: List[str] = None
    
    # Platform Settings
    youtube_channel_id: str = ""
    tiktok_account: str = ""
    
    def __post_init__(self):
        if self.primary_keywords is None:
            self.primary_keywords = [
                "${NEW_NICHE}",
                "${NICHE_TITLE}",
                # Add your keywords here
            ]
        
        if self.secondary_keywords is None:
            self.secondary_keywords = []
        
        if self.own_product_keywords is None:
            self.own_product_keywords = []


# Content Hooks for ${NICHE_TITLE}
CONTENT_HOOKS = [
    "Nobody talks about this...",
    "The truth about ${NICHE_TITLE}...",
    "What experts don't want you to know...",
    "I discovered something about ${NICHE_TITLE}...",
    "This changed everything for me...",
]

# Video Frameworks
VIDEO_FRAMEWORKS = [
    "problem_solution",      # Problem → Agitate → Solution
    "myth_busting",          # Common myths debunked
    "step_by_step",          # Tutorial format
    "comparison",            # X vs Y
    "story_driven",          # Personal narrative
]

# Monetization Routes
MONETIZATION = {
    "affiliate": {
        "primary": [],  # Add ClickBank/Digistore24 product IDs
        "backup": [],
    },
    "own_product": {
        "name": "",
        "url": "",
        "keywords": [],
    },
    "email": {
        "lead_magnet": "",
        "sequence_id": "",
    }
}


# Export config
NICHE_CONFIG = NicheConfig()
EOF

echo -e "${GREEN}✅ Niche configuration created${NC}"

# Step 5: Create .env.example for new niche
echo "🔐 Creating environment template..."

cat > "${TARGET_DIR}/.env.${NEW_NICHE}" << EOF
# ============================================================
# MONEY MACHINE - ${NICHE_UPPER} NICHE
# Environment Variables
# ============================================================

# Niche Identifier
NICHE_NAME=${NEW_NICHE}
NICHE_TAG=${NICHE_UPPER}_01

# Core Infrastructure (same as main)
N8N_ENCRYPTION_KEY=
WEBHOOK_URL=
DATABASE_URL=
REDIS_URL=

# Content APIs
REDDIT_CLIENT_ID=
REDDIT_CLIENT_SECRET=
PEXELS_API_KEY=
PIXABAY_API_KEY=

# Platform - YouTube (new channel for this niche)
YOUTUBE_CLIENT_ID=
YOUTUBE_CLIENT_SECRET=
YOUTUBE_REFRESH_TOKEN=
YOUTUBE_CHANNEL_ID=

# Notifications
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=

# Monetization
STRIPE_API_KEY=
PAYPAL_CLIENT_ID=
PAYPAL_CLIENT_SECRET=
CLICKBANK_CLERK_KEY=
SYSTEME_API_KEY=

# Optional
OPENAI_API_KEY=
ELEVENLABS_API_KEY=
EOF

echo -e "${GREEN}✅ Environment template created${NC}"

# Step 6: Initialize new git repo
echo "📦 Initializing git repository..."
cd "$TARGET_DIR"
git init
git add .
git commit -m "🚀 Initialize Money Machine - ${NICHE_TITLE} Clone"
echo -e "${GREEN}✅ Git repository initialized${NC}"

# Step 7: Create data directories
echo "📁 Creating data directories..."
mkdir -p "${TARGET_DIR}/data/logs"
mkdir -p "${TARGET_DIR}/data/metrics"
mkdir -p "${TARGET_DIR}/data/reports"
mkdir -p "${TARGET_DIR}/data/cache"
mkdir -p "${TARGET_DIR}/data/videos"
mkdir -p "${TARGET_DIR}/config"
echo -e "${GREEN}✅ Data directories created${NC}"

# Final Summary
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}🎉 CLONE COMPLETE: Money Machine - ${NICHE_TITLE}${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo "📍 Location: ${TARGET_DIR}"
echo ""
echo "📋 Next Steps:"
echo "  1. cd ${TARGET_DIR}"
echo "  2. Edit config/niche_config.py with your keywords"
echo "  3. Copy .env.${NEW_NICHE} to .env and fill in API keys"
echo "  4. Create new YouTube channel for this niche"
echo "  5. Set up new Systeme.io funnels"
echo "  6. Deploy to Railway as separate project"
echo ""
echo "💡 Tip: Each clone should have:"
echo "  - Separate YouTube channel"
echo "  - Separate email list"
echo "  - Separate affiliate accounts (or same, tracked by tag)"
echo ""
echo -e "${BLUE}Revenue from this clone is additive, not replacement.${NC}"
echo "============================================"
